#!/usr/bin/env tsx

/**
 * Генератор статического индекса tools
 *
 * Извлекает метаданные из всех tools и генерирует TypeScript файл
 * с pre-computed данными для быстрого поиска
 *
 * Запускается автоматически перед build: "prebuild": "tsx scripts/generate-tool-index.ts"
 *
 * Responsibilities:
 * - Извлечение статических METADATA из tool классов
 * - Токенизация имён и описаний
 * - Генерация TypeScript файла с индексом
 * - Валидация наличия METADATA во всех tools
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

// Импортируем tool classes (без инстанцирования)
import { TOOL_CLASSES } from '../src/composition-root/definitions/tool-definitions.js';
import type { StaticToolMetadata, ToolCategory } from '../src/mcp/tools/base/tool-metadata.js';
import type { StaticToolIndex } from '../src/mcp/search/types.js';

/**
 * Интерфейс для tool класса со статическими метаданными
 */
interface ToolWithMetadata {
  METADATA: StaticToolMetadata;
}

/**
 * Токенизация текста
 *
 * - Приведение к lowercase
 * - Замена разделителей на пробелы
 * - Разбиение по non-word символам
 * - Удаление пустых токенов
 */
function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[_-]/g, ' ')
    .split(/\W+/)
    .filter((token) => token.length > 0);
}

/**
 * Получить краткое описание (первое предложение)
 */
function getShortDescription(description: string): string {
  const firstSentence = description.split(/[.!?]/)[0];
  return firstSentence ? firstSentence.trim() : description;
}

/**
 * Генерация статического индекса
 */
function generateIndex(): StaticToolIndex[] {
  const index: StaticToolIndex[] = [];

  for (const ToolClass of TOOL_CLASSES) {
    // Проверяем наличие статических метаданных
    if (!('METADATA' in ToolClass)) {
      throw new Error(
        `❌ ${ToolClass.name} must have static METADATA property for index generation.\n` +
          `   Add: static readonly METADATA = { name, description, category, tags, isHelper }`
      );
    }

    const metadata = (ToolClass as unknown as ToolWithMetadata).METADATA;

    // Валидация метаданных
    if (!metadata.name || typeof metadata.name !== 'string') {
      throw new Error(`❌ ${ToolClass.name}: METADATA.name is required and must be a string`);
    }

    if (!metadata.description || typeof metadata.description !== 'string') {
      throw new Error(
        `❌ ${ToolClass.name}: METADATA.description is required and must be a string`
      );
    }

    if (!metadata.category) {
      throw new Error(`❌ ${ToolClass.name}: METADATA.category is required`);
    }

    if (!Array.isArray(metadata.tags)) {
      throw new Error(`❌ ${ToolClass.name}: METADATA.tags must be an array`);
    }

    if (typeof metadata.isHelper !== 'boolean') {
      throw new Error(`❌ ${ToolClass.name}: METADATA.isHelper must be a boolean`);
    }

    // Создаём индексную запись
    index.push({
      name: metadata.name,
      category: metadata.category,
      tags: metadata.tags,
      isHelper: metadata.isHelper,
      nameTokens: tokenize(metadata.name),
      descriptionTokens: tokenize(metadata.description),
      descriptionShort: getShortDescription(metadata.description),
    });
  }

  return index;
}

/**
 * Генерация TypeScript файла с индексом
 */
function generateTypeScriptFile(index: StaticToolIndex[]): string {
  // Преобразуем индекс в TypeScript код с правильными типами
  const indexCode = index
    .map((tool) => {
      const tagsStr = tool.tags.map((t) => `'${t}'`).join(', ');
      const nameTokensStr = tool.nameTokens.map((t) => `'${t}'`).join(', ');
      const descTokensStr = tool.descriptionTokens.map((t) => `'${t}'`).join(', ');

      return `  {
    name: '${tool.name}',
    category: ToolCategory.${String(tool.category).toUpperCase().replace(/-/g, '_')},
    tags: [${tagsStr}],
    isHelper: ${tool.isHelper},
    nameTokens: [${nameTokensStr}],
    descriptionTokens: [${descTokensStr}],
    descriptionShort: '${tool.descriptionShort.replace(/'/g, "\\'")}',
  }`;
    })
    .join(',\n');

  return `/**
 * Статический индекс tools для поиска
 *
 * 🤖 AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-tool-index.ts
 *
 * Regenerate: npm run generate:index
 */

import { ToolCategory } from '@mcp/tools/base/tool-metadata.js';

/**
 * Статический индекс tool для compile-time генерации
 *
 * Содержит pre-computed данные для быстрого поиска
 */
export interface StaticToolIndex {
  /** Имя инструмента */
  name: string;

  /** Категория */
  category: ToolCategory;

  /** Теги для поиска */
  tags: string[];

  /** Helper или API tool */
  isHelper: boolean;

  /** Pre-computed токены из имени */
  nameTokens: string[];

  /** Pre-computed токены из описания */
  descriptionTokens: string[];

  /** Краткое описание (без inputSchema) */
  descriptionShort: string;
}

/**
 * Статический индекс всех tools
 *
 * Используется ToolSearchEngine для быстрого поиска
 */
export const TOOL_SEARCH_INDEX: readonly StaticToolIndex[] = [
${indexCode}
] as const;
`;
}

/**
 * Главная функция
 */
async function main(): Promise<void> {
  console.log('🔍 Генерация статического индекса tools...\n');

  try {
    // Генерируем индекс
    const index = generateIndex();

    console.log(`✅ Проиндексировано tools: ${index.length}`);
    console.log();

    // Выводим статистику
    const categories = new Map<string, number>();
    const helperCount = index.filter((t) => t.isHelper).length;

    for (const tool of index) {
      const count = categories.get(tool.category) || 0;
      categories.set(tool.category, count + 1);
    }

    console.log('📊 Статистика:');
    console.log(`   API tools: ${index.length - helperCount}`);
    console.log(`   Helper tools: ${helperCount}`);
    console.log();
    console.log('   По категориям:');
    for (const [category, count] of Array.from(categories.entries()).sort()) {
      console.log(`     - ${category}: ${count}`);
    }
    console.log();

    // Генерируем TypeScript файл
    const output = generateTypeScriptFile(index);

    // Определяем путь к выходному файлу
    const outputPath = path.join(
      path.dirname(fileURLToPath(import.meta.url)),
      '../src/mcp/search/generated-index.ts'
    );

    // Записываем файл
    fs.writeFileSync(outputPath, output, 'utf-8');

    // Форматируем файл через Prettier для консистентности
    try {
      execSync(`npx prettier --write "${outputPath}"`, { stdio: 'pipe' });
    } catch (error) {
      console.warn('⚠️  Не удалось отформатировать файл через Prettier');
    }

    console.log(`✅ Индекс сохранён: ${path.relative(process.cwd(), outputPath)}`);
    console.log('   Размер:', Buffer.byteLength(output, 'utf8'), 'bytes');
    console.log();
    console.log('✨ Генерация завершена успешно!');
  } catch (error) {
    console.error('❌ Ошибка при генерации индекса:\n');

    if (error instanceof Error) {
      console.error(error.message);
      if (error.stack) {
        console.error('\nStack trace:');
        console.error(error.stack);
      }
    } else {
      console.error(error);
    }

    process.exit(1);
  }
}

// Запуск
main().catch((error) => {
  console.error('❌ Необработанная ошибка:', error);
  process.exit(1);
});
