/**
 * Статический индекс tools для поиска
 *
 * 🤖 AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated at: 2025-11-14T17:16:34.607Z
 * Generated by: scripts/generate-tool-index.ts
 *
 * Regenerate: npm run generate:index
 */

import { ToolCategory } from '@mcp/tools/base/tool-metadata.js';

/**
 * Статический индекс tool для compile-time генерации
 *
 * Содержит pre-computed данные для быстрого поиска
 */
export interface StaticToolIndex {
  /** Имя инструмента */
  name: string;

  /** Категория */
  category: ToolCategory;

  /** Теги для поиска */
  tags: string[];

  /** Helper или API tool */
  isHelper: boolean;

  /** Pre-computed токены из имени */
  nameTokens: string[];

  /** Pre-computed токены из описания */
  descriptionTokens: string[];

  /** Краткое описание (без inputSchema) */
  descriptionShort: string;
}

/**
 * Статический индекс всех tools
 *
 * Используется ToolSearchEngine для быстрого поиска
 */
export const TOOL_SEARCH_INDEX: readonly StaticToolIndex[] = [
  {
    name: 'yandex_tracker_ping',
    category: ToolCategory.USERS,
    tags: ['ping', 'health', 'check', 'connection', 'diagnostics'],
    isHelper: false,
    nameTokens: ['yandex', 'tracker', 'ping'],
    descriptionTokens: ['api', 'oauth'],
    descriptionShort: 'Проверка доступности API Яндекс',
  },
  {
    name: 'yandex_tracker_get_issues',
    category: ToolCategory.ISSUES,
    tags: ['issue', 'get', 'batch', 'read'],
    isHelper: false,
    nameTokens: ['yandex', 'tracker', 'get', 'issues'],
    descriptionTokens: ['batch'],
    descriptionShort: 'Получить задачи по ключам (batch операция)',
  },
  {
    name: 'yandex_tracker_find_issues',
    category: ToolCategory.ISSUES,
    tags: ['issue', 'find', 'search', 'jql', 'query'],
    isHelper: false,
    nameTokens: ['yandex', 'tracker', 'find', 'issues'],
    descriptionTokens: ['jql'],
    descriptionShort: 'Найти задачи по JQL запросу',
  },
  {
    name: 'yandex_tracker_get_issue_url',
    category: ToolCategory.URL_GENERATION,
    tags: ['url', 'link', 'helper', 'issue'],
    isHelper: true,
    nameTokens: ['yandex', 'tracker', 'get', 'issue', 'url'],
    descriptionTokens: ['url'],
    descriptionShort: 'Получить URL задачи в Яндекс',
  },
  {
    name: 'yandex_tracker_demo',
    category: ToolCategory.DEMO,
    tags: ['demo', 'example', 'test'],
    isHelper: true,
    nameTokens: ['yandex', 'tracker', 'demo'],
    descriptionTokens: [],
    descriptionShort: 'Демонстрационный инструмент для тестирования',
  },
  {
    name: 'yandex_tracker_search_tools',
    category: ToolCategory.SEARCH,
    tags: ['search', 'tools', 'discovery', 'find', 'helper'],
    isHelper: true,
    nameTokens: ['yandex', 'tracker', 'search', 'tools'],
    descriptionTokens: ['mcp'],
    descriptionShort: 'Поиск доступных MCP инструментов по запросу',
  },
] as const;
